//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DWConfigurationEntities2 : DbContext
    {
        public DWConfigurationEntities2()
            : base("name=DWConfigurationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compute_node> compute_node { get; set; }
        public virtual DbSet<configuration_properties> configuration_properties { get; set; }
        public virtual DbSet<database_file> database_file { get; set; }
        public virtual DbSet<distribution> distributions { get; set; }
        public virtual DbSet<filegroup> filegroups { get; set; }
        public virtual DbSet<node> nodes { get; set; }
        public virtual DbSet<pdw_sp_configure> pdw_sp_configure { get; set; }
        public virtual DbSet<version_history> version_history { get; set; }
    }
}
