//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration_properties
    {
        public string id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public string @default { get; set; }
        public short protection { get; set; }
        public short access { get; set; }
        public string datatype { get; set; }
    }
}
