//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdw_sp_configure
    {
        public string name { get; set; }
        public Nullable<int> minimum { get; set; }
        public Nullable<int> maximum { get; set; }
        public Nullable<int> config_value { get; set; }
        public Nullable<int> run_value { get; set; }
    }
}
